### ISSUE TITLE
Todo list before release v1.2.0.

### ISSUE THREAD

**Issue by vudsen** [nextjs-particlex-theme/particlex#6]
- [x] `GithubCodeBlock` in mdx may not parse correctly.
- [x] In light mode, the Header in home page is not white text.
- [x] When use `h4` in markdown, the text color in Toc is darker than `h3`.
